apps:
  - script: 'npm'
    args: 'run start'
    cwd: './back-end'
    name: 'server'
  - script: 'npm'
    args: 'run start'
    cwd: './nuxt-front-end'
    max_memory_restart: '200M'
    name: 'nuxt'
