version: '3.1'

services:
  api-server:
    container_name: api-server
    restart: always
    image: bboy81905/storeweb_api-server
    volumes:
      - ../backup/public:/api-server/public
      - ../backup/db:/api-server/db
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      NODE_ENV: production
    logging:
      driver: 'json-file'
      options:
        max-file: '3'
        max-size: '10m'
  nuxt-server:
    container_name: nuxt-server
    restart: always
    image: bboy81905/storeweb_nuxt-server
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NODE_ENV: production
      prodUrl: ${prodUrl}
      prodNuxtURL: ${prodUrl}
    logging:
      driver: 'json-file'
      options:
        max-file: '3'
        max-size: '10m'
  reverse-proxy:
    container_name: reverse-proxy
    restart: always
    image: nginx:1.14
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    logging:
      driver: 'json-file'
      options:
        max-file: '3'
        max-size: '10m'
    depends_on:
      - api-server
      - nuxt-server
