version: '3.7'

services:
  api-server:
    container_name: api-server
    restart: always
    image: bboy81905/storeweb_api-server
    volumes:
      - ../backup/public:/api-server/public
      - ../backup/db:/api-server/db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api-server.rule= PathPrefix(`/api`,`/apipost`) || (Path(`/login`) && Method(`POST`))'
      - 'traefik.http.services.api-server.loadbalancer.server.port=8080'
    environment:
      PORT: 8080
      NODE_ENV: production

  nuxt-server:
    container_name: nuxt-server
    restart: always
    image: bboy81905/storeweb_nuxt-server
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nuxt-server.rule=Host(`localhost`)'
      - 'traefik.http.services.nuxt-server.loadbalancer.server.port=3000'
    environment:
      PORT: 3000
      NODE_ENV: production
      prodUrl: ${prodUrl}
      prodNuxtURL: ${prodUrl}

  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'

networks:
  default:
    external:
      name: traefik_default
