name: CICD

on:
  push:
    branches: [feature/cicd]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build nuxt-front-end docker image
        run: cd ./nuxt-front-end && docker build -t bboy81905/storeweb_nuxt-server .
      - name: Build back-end  docker image
        run: cd ./back-end && docker build -t bboy81905/storeweb_api-server .
      - name: Publish image to docker hub
        run: docker push bboy81905/storeweb_nuxt-server:latest&& docker push bboy81905/storeweb_api-server:latest
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull new Script
        run: cd /home/ubuntu/storeWeb/ && git checkout feature/cicd && git pull
      - name: Run deploy script
        run: cd /home/ubuntu/storeWeb && . ./deploy.sh
