name: CICD

on:
  push:
    branches: [master]

jobs:
  deploy-prod:
    runs-on: [aws-ec2-prod]
    environment: prod
    steps:
      - name: Pull new Script
        run: cd /home/ubuntu/storeWeb/ && git checkout master && git pull
      - name: Run shut down script
        run: cd /home/ubuntu/storeWeb && . ./deploy.sh
      - name: Run docker-compose
        run: cd /home/ubuntu/storeWeb && sudo prodUrl=${{ secrets.PROD_URL }} docker-compose up -d
